version: '3'
services:
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: json-file
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  kib:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
  kc:
    container_name: kc
    image: quay.io/keycloak/keycloak:11.0.0
    ports:
      - 8780:8080
      - 8443:8443
    volumes:
      - /c/Users/wjose/Downloads/docker-shared:/etc/x509/https
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  zip:
    container_name: zip
    image: openzipkin/zipkin
    ports:
      - 9412:9411
